### ISSUE TITLE
Update page doesn't show newest release version and notes

### ISSUE THREAD

**Issue by petewalker** [atom/about#44]
From:  atom/atom#12311

### Description

The atom updater, when there's a new update, always shows the currently-installed vesion.

### Steps to Reproduce

1. Launch atom
1. **DO NOT** open the about page
1. Wait until there's a new release
1. Click the Squirrel icon in the lower-right

**Expected behavior:**

The Restart & Update section on the About tab should show the newest release version and link to its notes.

**Actual behavior:**

The Restart & Update section shows the **currently-installed** version number and links to the **currently-installed** version's release notes.

![image](https://cloud.githubusercontent.com/assets/453816/20427183/91389bee-ad7a-11e6-86e4-c79ab7c5c4ca.png)

### Versions

Windows version
```
ver
Microsoft Windows [Version 10.0.10586]
```

Atom version
```
atom --version
Atom: 1.9.2
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0
```

Atom package manager version
```
apm --version
apm: 1.10.0
npm: 2.13.3
node: 0.10.40
python
git
Visual Studio
```

Since I'm on Windows, the `apm --version` colors may not be displaying correctly. I had a hard time reading the Node version output for that command.

Also, as far as I know, this has been happening at least since Atom 1.5 or 1.6. I just didn't think to report it until now.

**Comment by petewalker** [comment]
Based on my analysis, I've found the following:

The logic checking whether there is an update available seems to vary in different parts of the plugin:

**main.js** appears to listen to the `atom.onUpdateAvailable` event, and then caches the available version in localStorage.

https://github.com/atom/about/blob/v1.7.2/lib/main.js#L28

```js
this.subscriptions.add(atom.onUpdateAvailable(({releaseVersion}) => {
  window.localStorage.setItem(AvailableUpdateVersion, releaseVersion)
  this.showStatusBarIfNeeded()
}))
```

However, **update-manager.js** listens for a completely different event, `atom.autoUpdater.onDidCompleteDownloadingUpdate`:

https://github.com/atom/about/blob/v1.7.2/lib/update-manager.js#L32

```js
listenForAtomEvents () {
  this.subscriptions = new CompositeDisposable()

  this.subscriptions.add(
    //...
    atom.autoUpdater.onDidCompleteDownloadingUpdate((detail) => {
      let {releaseVersion} = detail
      this.setAvailableVersion(releaseVersion)
    })
    //...
  )
}
```

---

My suspicion is that the `atom.onUpdateAvailable` event is being fired/received, but the `atom.autoUpdater.onDidCompleteDownloadingUpdate` event is not.

This is resulting in the inconsistent state that's then visible in the about page.

**Comment by JSn1nj4** [comment]
Would be awesome if this leads to fixing the issue.

Also, I didn't realize there was a repo specifically for "About". Thanks for posting this.

**Comment by cbarrick** [comment]
I've encountered this issue forever, but it seems fixed now
![atom-about](https://cloud.githubusercontent.com/assets/271982/20468272/fd5e4654-af62-11e6-93f1-6ead3824d258.png)

**Comment by petewalker** [comment]
It's not fixed for me - I saw this issue as recently as **1.12.3** upgrading to **1.12.4** (as you've shown above).

The screenshot and version numbers I took from above are from the original issue raised in the atom/atom repo.

Based on my analysis, it would still make sense for the issue being sporadic - maybe that event gets fired sometimes, but not always?

**Comment by petewalker** [comment]
In fact, still there in 1.12.4:

<img width="634" alt="screen shot 2016-11-21 at 10 35 20" src="https://cloud.githubusercontent.com/assets/453816/20479501/5948bce2-afd6-11e6-83ae-79dc0f03281e.png">

**Comment by petewalker** [comment]
The above screenshot was on Mac. I had the about page closed whilst the update was downloading. Below is my Windows VM - I had the about page open:

<img width="559" alt="screen shot 2016-11-21 at 10 51 05" src="https://cloud.githubusercontent.com/assets/453816/20480001/7ec848c8-afd8-11e6-9086-2aa89f78ae90.png">

**Comment by petewalker** [comment]
Right, so my suspicion is correct here.

The subscriptions in https://github.com/atom/about/blob/v1.7.2/lib/update-manager.js#L32 aren't added until the about page is opened.

This means that the version is only displayed correctly if the about page had already been opened in the current editor session before the update was downloaded.

Presumably the fix would be to add the subscriptions regardless of whether the about page has been opened?

**Comment by a7madgamal** [comment]
same here for the last 4-5 updates on mac
